### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by Haaroon** [mirleft/btc-pinata#10]
It expired earlier this year

**Comment by hannesm** [comment]
please read `ownme.ipredator.se` carefully, thanks.

```
This page is also available via HTTPS. It will present a certificate signed by the same authority that Piñata expects to sign all of the incoming requests, so your browser will complain. The purpose of HTTPS is to allow checking of interoperability with our TLS implementation.
```

**Comment by Haaroon** [comment]
Thats expired too, so you are saying the expiration date of the certificates doesnt remotely matter?

**Comment by hannesm** [comment]
since it is a self-signed certificate (or from a CA you shouldn't trust either), it shouldn't matter.  does it to you?

**Comment by Haaroon** [comment]
I keep getting `<< TLS 1.2 Alert [length 0002], fatal certificate_expired` whenever i try to connect...removed

**Comment by hannesm** [comment]
which commandline do you use (i.e. which port do you try to connect to)?  I just tried to short-circuit the server and client on port 10000 and 10002, which still seems to work, so I don't see any reason to act.  feel free to mail me (hannes AT mehnert DOT org, 0xBC896588DF7C28EE).
